# Generated by Django 6.0.3 on 2026-04-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_staff_delete_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
