# Generated by Django 6.0.3 on 2026-04-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_alter_staff_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
