# Generated by Django 6.0.3 on 2026-04-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0004_electionlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('aadhaar', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
