# Generated by Django 6.0.3 on 2026-04-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0005_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='marital_status',
            field=models.CharField(default='Single', max_length=10),
        ),
    ]
