# Generated by Django 6.0.3 on 2026-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0007_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='candidate_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
