# Generated by Django 6.0.3 on 2026-04-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0008_candidate_delete_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.electionlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.candidate')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.electionlocation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.people')),
            ],
            options={
                'unique_together': {('person',)},
            },
        ),
    ]
