# Generated by Django 6.0.3 on 2026-04-16 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0009_electionsettings_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voteapp.electionlocation'),
        ),
    ]
