# Generated by Django 6.0.3 on 2026-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0011_election_electioncandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people_photos/'),
        ),
    ]
