# Generated by Django 6.0.3 on 2026-04-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0012_people_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
