# Generated by Django 6.0.3 on 2026-05-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0013_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voted_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='location',
        ),
    ]
